FROM alpine:latest
ARG TF_VERSION
RUN apk -U upgrade && apk add --no-cache bash curl &&\
    TE_URL=$(wget -q -O - https://api.github.com/repos/tfutils/tfenv/releases/latest | grep '"zipball_url":' | cut -d '"' -f 4) &&\
    wget -q -O - ${TE_URL} | unzip -q -d $HOME/tfenv - &&\
    ln -fs ${HOME}/tfenv/*/bin/* /usr/bin &&\
    chmod +x ${HOME}/tfenv/*/bin/* ${HOME}/tfenv/*/libexec/* &&\
    tfenv install ${TF_VERSION:-1.0.2} &&\
    tfenv use ${TF_VERSION:-1.0.2}
#EOF